### PR TITLE
#167484543 finished setting up react router

### PR DESCRIPTION
**Pull request by placideirandora**
#### What does this PR do?
It configures **Authors Haven** to use **React Router**.

#### Description of Task to be done?
1. Installing required dependency - react-router-dom.
2. Adding components for testing the react-router functionality.
3. Updating the root component to implement the react-router.

#### How should this be manually tested?
1. Clone this branch.
2. Do **npm install**.
3. Do *npm start** and you should see the landing page.
4. Click on the **About** navigation link and check if the body content changes and click on the **Home** navigation link or the  **AH** logo and check if the body content changes as well.

#### Screenshots
Screen Shot 2019-09-24 at 17 23 16
Screen Shot 2019-09-24 at 17 23 32
Screen Shot 2019-09-24 at 17 27 07

### CODE REVIEW

**Review by harerakalex — APPROVED** [review]
LGTM

**Comment by clemwek** [comment]
Move the about and home files into `src/feature/home` and `src/feature/about` Then the Nav file `src/app/routes`.

**Comment by placideirandora** [comment]
> Move the about and home files into `src/feature/home` and `src/feature/about` Then the Nav file `src/app/routes`.

Thanks. I'm gonna implement the feedback.

**Comment by placideirandora** [comment]
> Move the about and home files into `src/feature/home` and `src/feature/about` Then the Nav file `src/app/routes`.

I have implemented the feedback.

**Review by clemwek — APPROVED** [review]

**Pull request merged**
