### PR TITLE
#167484553 - Comment on an article

### PR DESCRIPTION
**Pull request by malaba6**
### What does this PR do?
- Adds page to comment on an article's UI
- UI responsiveness

### Description of Task to be completed?
- Create `ComponentComponent`
- Add responsiveness to the UI

### What are the relevant pivotal tracker stories?
[Comment on an article](https://www.pivotaltracker.com/story/show/##167484553)

### Screenshots? 
Desktop

Screen Shot 2019-10-21 at 16 35 54
Mobile

Screen Shot 2019-10-21 at 16 37 09

### CODE REVIEW

**Review by placideirandora — COMMENTED** [review]
The responsiveness looks good.

**Review by raymond42 — COMMENTED** [review]
So far so good.

**Review by Jkadhuwa — COMMENTED** [review]
could you align the thumbs down and the count.

**Comment by malaba6** [comment]
> could you align the thumbs down and the count.

I will... Thanx

**Comment by harerakalex** [comment]
LGTM

**Review by placideirandora — APPROVED** [review]
Everything works as expected.

**Pull request merged**
